/**
 * build.js — Bundles all ES modules into a single app.js file
 * Run: node build.js
 */
const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'src');
const outFile = path.join(__dirname, 'app.js');

// Files in dependency order
const files = [
  'constants.js',
  'zobrist.js',
  'board.js',
  'moveGen.js',
  'evaluation.js',
  'opening.js',
  'notation.js',
  'search.js',
  'engine.js',
  'network.js',
  'game.js',
  'renderer.js',
  'ui.js',
  'main.js',
];

let bundle = '/* ============================================================\n';
bundle += ' *  Cờ Vua AI — Bundled application\n';
bundle += ' *  Auto-generated by build.js\n';
bundle += ' * ============================================================ */\n\n';
bundle += '(function() {\n"use strict";\n\n';

for (const file of files) {
  const filePath = path.join(srcDir, file);
  let content = fs.readFileSync(filePath, 'utf8');
  
  // Remove import statements
  content = content.replace(/^import\s+\{[^}]*\}\s+from\s+['"][^'"]+['"];?\s*$/gm, '');
  content = content.replace(/^import\s+['"][^'"]+['"];?\s*$/gm, '');
  
  // Remove export keywords but keep the declarations
  content = content.replace(/^export\s+(?=function|class|const|let|var|default)/gm, '');
  content = content.replace(/^export\s+\{[^}]*\};?\s*$/gm, '');
  
  bundle += `// ─── ${file} ${'─'.repeat(Math.max(1, 50 - file.length))}──\n`;
  bundle += content.trim() + '\n\n';
}

bundle += '\n})();\n';

fs.writeFileSync(outFile, bundle, 'utf8');
console.log(`✅ Bundled ${files.length} files → ${outFile}`);
console.log(`   Size: ${(Buffer.byteLength(bundle) / 1024).toFixed(1)} KB`);
